#define PIN_ULTRASONIC_SIG 14
#define PIN_LED_BAR_DCKI 13
#define PIN_LED_BAR_DI 12

#define WIFI_SSID "WIFI_SSID"
#define WIFI_PASSWORD "WIFI_PASSWORD"
#define FIREBASE_HOST "FIREBASE_HOST"
#define FIREBASE_SECRET "FIREBASE_SECRET"

#define WAITING_LIMIT_FOR_WIFI_CONNECTION_MS 20000
#define DEFAULT_TIME_TO_DISCHARGE_MS 60000
#define DEFAULT_TIME_TO_RECHARGE_MS 10000
#define DEFAULT_THRESHOLD_DISTANCE_CM 42
